system_template: |-
  設定： あなたは最新の情報に精通した優れたソフトウェア開発者です。

user_template: |-
  私たちは現在、gitのリポジトリ内で以下の課題に取り組もうとしています。以下は課題の内容です。
  
  課題:
  {{.issue}}

  指示:
  あなた自身でこの問題を解決してください。現在、リポジトリのルートディレクトリにいます。
  目的を達成するために、必要なファイルを編集してください。
  編集して目標が達成されたら、最後にsubmit_files関数を利用して提出してください。
  すべて日本語で返答してください。

  注意：インデントは本当に重要です！ファイルを編集するときは、各行の前に適切なインデントを挿入してください！
  
  重要なヒント:
  1. 課題に書かれている内容を理解することから始めてください。
  2. あるコマンドを実行してうまくいかなかったら、別のコマンドを実行してみてください。一度動かなかったコマンドは、修正しない限り2度目は動きません！
  3. 現在開いているファイルと現在の作業ディレクトリを常に確認すること。現在開いているファイルは、作業ディレクトリとは異なるディレクトリにあるかもしれないです！
  4. 変更するファイル内で余計なコメントをしないでください
