services:
  agent:
    build:
      context: .
      dockerfile: dev-compose.Dockerfile
      target: development
    volumes:
      - ./:/usr/local/agent
      - agent-go-mod:/go/pkg/mod
    ports:
      - "32345:2345"
    networks:
      - agent-net
    cap_add:
      - SYS_PTRACE
volumes:
  agent-go-mod:
networks:
  agent-net:
    driver: bridge
