services:
  mkdocs:
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: "mkdocs serve --dev-addr=0.0.0.0:8000"
